# key : val  # dummy variable if params is empty & we try to read it we will get an error

AUGMENTATION: True
IMAGE_SIZE: [224,224,3]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01