artifacts_root: artifacts


data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL: https://github.com/Priyanshu1303d/Chicken_Disease_Classification/raw/refs/heads/main/Data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  update_base_model_path : artifacts/prepare_base_model/base_model_updated.h5

prepare_callbacks:
  root_dir : artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5
  # after training some epochs it will same the model